name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda (Python 3.12)
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: deal
          python-version: "3.12"
          auto-update-conda: true
          channels: conda-forge,defaults

      - name: Install FLARE build dependencies
        run: |
          conda install -y gcc gxx cmake openmp liblapacke openblas -c conda-forge

      - name: Install FLARE 1.3.3b
        run: |
          git clone https://github.com/mir-group/flare.git -b 1.3.3b
          cd flare
          pip install .

      - name: Install DEAL
        run: |
          pip install .

      - name: Run DEAL tests
        run: |
          cd tests
          bash run_all.sh
